### ISSUE TITLE
Loss is' Nan '

### ISSUE THREAD

**Issue by TWJ718925** [sommerschield/ancient-text-restoration#10]
Hello, I used your open code and dataset training, and when I iterated 120 times, the loss was abnormal. Why?How to solve it? thank you.

**Comment by iassael** [comment]
Hi @TWJ718925, with the right dependencies the model training works properly, I just verified it for you.

I would recomend you to make sure you have the right dependencies installed. (I just updated the TF v1.15 dependency in the requirements.txt.). Another place to check would be your dataset, as it might be corrupted (funny to say that for a dataset of currupted instcriptions).

Finally, there are many warnings and the codebase needs to be migrated to TF v2 at some point, some help with this would be fantastic and deeply appreciated :)

**Comment by TWJ718925** [comment]
Hello, I have followed requirements.txt Install the correct dependency, the dataset uses what you provide, but still can't solve the loss exception.
