### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'contrib'

### ISSUE THREAD

**Issue by TWJ718925** [sommerschield/ancient-text-restoration#15]
AttributeError: module 'tensorflow' has no attribute 'contrib',how to solve this because the tensorflow version is too high?

**Comment by iassael** [comment]
Hi TWJ718925, exactly, the error is caused by a more recent version of tensorflow. You could try using version 1.15. The full list of dependancies and their versions is outlined in `requirements.txt`

**Comment by TWJ718925** [comment]
But when I use tensorflow 1.15.2, the version is too low to run，“ImportError: this version of Tensorflow Dataset requires Tensorflow version >= 2.1.0”

**Comment by iassael** [comment]
Do you face this problem during raining or in the colab?

**Comment by TWJ718925** [comment]
The tensorflow version I encountered in the process of training the model was too low, requiring TensorFlow version>=2.1.0.

**Comment by iassael** [comment]
The issue comes from the conflicting tensor2tensor dependecy and we just pushed an update to remove that. Could you give it a try? Thanks
