### ISSUE TITLE
Problems with training

### ISSUE THREAD

**Issue by TWJ718925** [sommerschield/ancient-text-restoration#17]
The data set is normal and the environment is built according to the requirements, but during training, the loss appears abnormal "nan". How to solve it?

**Comment by iassael** [comment]
Hi TWJ718925 I'm sorry you are getting this, I just rerun it and it works normally in the machine we ran the experiments. My guess would be your CUDA version, but in general old TF1 code has been increasingly difficult to run nowadays.

**Comment by TWJ718925** [comment]
What is the version number of CUDA you are using?

**Comment by iassael** [comment]
Hey TWJ718925, could you please contact me at the email found on my webpage (https://www.assael.gr/) to resolve your issue? I'd be very happy to help.
