### ISSUE TITLE
Restoration of Chinese characters in ancient books

### ISSUE THREAD

**Issue by dan326326** [sommerschield/ancient-text-restoration#21]
Hello, can your code be applied to the repair of Chinese characters in ancient books

**Comment by sommerschield** [comment]
Hi dan326326. Have these ancient Chinese documents been digitised and transcribed? 
Pythia's architecture may be applied to restore missing words/characters in texts written in any language and on any medium, including Chinese manuscripts - once the dataset in question has been cleaned and made machine actionable.
I hope this answers your question! Have a nice day

**Comment by dan326326** [comment]
thank you!
